// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {userconfig} from '../models';

export function LoadUserConfig():Promise<userconfig.UserConfig>;

export function SaveUserConfig():Promise<Error>;

export function SelectDirectory():Promise<string>;
