// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadUserConfig() {
  return window['go']['userconfig']['UserConfig']['LoadUserConfig']();
}

export function SaveUserConfig() {
  return window['go']['userconfig']['UserConfig']['SaveUserConfig']();
}

export function SelectDirectory() {
  return window['go']['userconfig']['UserConfig']['SelectDirectory']();
}
